let WIDTH = 400;
let HEIGHT = 400;

let PLAYERSIZE = 40;
let PLAYERSPEED = 0.06;
let DAMAGE = 1;

let GAPWIDTH = 66;
let GAPHEIGHT = 80;
let MAXOFFSET = 150;
let GAPDISTANCE = 200;

let OBSTACLESTARTSPEED = 0.1;

let GAPARRAYLENGTH = 6;

let SLOWMOSPEED = 0.4;
let NORMALSPEED = 1.0;
let SPEEDINCREASE = 0.7;
let SLOWMORECHARGESPEED = 0.5;
let SLOWMOCOST = -3;
let SLOWMOMINIMAL = 10;